from dataclasses import dataclass

@dataclass
class EngineArgs:
    model: str = ...
    served_model_name: str | list[str] | None = ...
    tokenizer: str | None = ...
    trust_remote_code: bool = ...
    dtype: str = ...
    seed: int = ...
    max_model_len: int | None = ...
    gpu_memory_utilization: float = ...
    enforce_eager: bool = ...
    tensor_parallel_size: int = ...
    pipeline_parallel_size: int = ...
    quantization: str | None = ...
    load_format: str = ...
    enable_sleep_mode: bool = ...
    enable_prefix_caching: bool | None = ...
    disable_hybrid_kv_cache_manager: bool = ...
    disable_log_stats: bool = ...
    max_num_batched_tokens: int | None = ...
    max_num_seqs: int | None = ...
    kv_cache_dtype: str = ...
    # `attention_backend` is an AttentionBackendEnum and `compilation_config` a
    # CompilationConfig; both live in vLLM modules we don't stub, so they land
    # here as `object` rather than being pinned to a guessed shape.
    attention_backend: object | None = ...
    compilation_config: object | None = ...
    # vLLM accepts either a KVTransferConfig or the plain dict form.
    kv_transfer_config: object | None = ...
