from typing import Any, Sequence

from torch import backends as backends
from torch import cuda as cuda
from torch import distributed as distributed

__version__: str

class version:
    cuda: str

class dtype: ...

bfloat16: dtype
float16: dtype
float32: dtype
float64: dtype
int8: dtype
int32: dtype
int64: dtype
long: dtype
uint8: dtype
uint16: dtype
uint32: dtype
uint64: dtype
float8_e4m3fn: dtype
float8_e5m2: dtype

class Tensor:
    shape: Sequence[int]
    dtype: dtype
    def __getitem__(self, key: Any) -> Tensor: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __lt__(self, other: Any) -> Tensor: ...
    def __le__(self, other: Any) -> Tensor: ...
    def __gt__(self, other: Any) -> Tensor: ...
    def __ge__(self, other: Any) -> Tensor: ...
    def to(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def cuda(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def detach(self) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def copy_(self, src: Tensor, non_blocking: bool = False) -> Tensor: ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def view(self, *shape: Any) -> Tensor: ...
    def reshape(self, *shape: Any) -> Tensor: ...
    def squeeze(self, dim: int = ...) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def permute(self, *dims: int) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def clamp(self, min: Any = None, max: Any = None) -> Tensor: ...
    def float(self) -> Tensor: ...
    def numpy(self) -> Any: ...
    def numel(self) -> int: ...
    def nelement(self) -> int: ...
    def element_size(self) -> int: ...
    def dim(self) -> int: ...
    def size(self, dim: int = ...) -> Any: ...
    @property
    def is_cuda(self) -> bool: ...
    @property
    def device(self) -> device: ...
    def __len__(self) -> int: ...
    def data_ptr(self) -> int: ...
    def tolist(self) -> Any: ...
    def abs(self) -> Tensor: ...
    def max(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def sum(self, dim: int = ...) -> Tensor: ...
    def item(self) -> float: ...

def tensor(data: Any, dtype: dtype | None = None, device: Any = None) -> Tensor: ...
def zeros(
    *size: Any,
    dtype: dtype | None = None,
    device: Any = None,
    pin_memory: bool = False,
) -> Tensor: ...
def empty(
    *size: Any,
    dtype: dtype | None = None,
    device: Any = None,
    pin_memory: bool = False,
) -> Tensor: ...
def cat(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
def stack(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
def from_numpy(ndarray: Any) -> Tensor: ...
def inference_mode() -> Any: ...
def compile(*args: Any, **kwargs: Any) -> Any: ...

class device:
    def __init__(self, type: str, index: int = ...) -> None: ...
