from contextlib import AbstractContextManager

class _DeviceProperties:
    total_memory: int

class Stream:
    def __init__(self, device: int | None = ..., priority: int = ...) -> None: ...
    def wait_stream(self, stream: Stream) -> None: ...
    def wait_event(self, event: Event) -> None: ...
    def record_event(self, event: Event | None = ...) -> Event: ...
    def synchronize(self) -> None: ...
    def query(self) -> bool: ...

class Event:
    def __init__(
        self,
        enable_timing: bool = ...,
        blocking: bool = ...,
        interprocess: bool = ...,
    ) -> None: ...
    def record(self, stream: Stream | None = ...) -> None: ...
    def wait(self, stream: Stream | None = ...) -> None: ...
    def synchronize(self) -> None: ...
    def query(self) -> bool: ...
    def elapsed_time(self, end_event: Event) -> float: ...

def is_available() -> bool: ...
def get_device_name(device: int) -> str: ...
def get_device_properties(device: int) -> _DeviceProperties: ...
def empty_cache() -> None: ...
def mem_get_info() -> tuple[int, int]: ...
def synchronize() -> None: ...
def max_memory_allocated() -> int: ...
def current_stream(device: int | None = ...) -> Stream: ...
def default_stream(device: int | None = ...) -> Stream: ...
def stream(stream: Stream | None) -> AbstractContextManager[None]: ...
def get_device_capability(device: object = None) -> tuple[int, int]: ...
